interface country {
  countryCode: string;
  countryName: string;
  ordinal: number;
}

export const CountryCodes: country[] = [
  { countryCode: "USA", countryName: "United States", ordinal: 1 },
  { countryCode: "ABW", countryName: "Aruba", ordinal: 999 },
  { countryCode: "AFG", countryName: "Afghanistan", ordinal: 999 },
  { countryCode: "AGO", countryName: "Angola", ordinal: 999 },
  { countryCode: "AIA", countryName: "Anguilla", ordinal: 999 },
  { countryCode: "ALA", countryName: "Åland Islands", ordinal: 999 },
  { countryCode: "ALB", countryName: "Albania", ordinal: 999 },
  { countryCode: "AND", countryName: "Andorra", ordinal: 999 },
  { countryCode: "ARE", countryName: "United Arab Emirates", ordinal: 999 },
  { countryCode: "ARG", countryName: "Argentina", ordinal: 999 },
  { countryCode: "ARM", countryName: "Armenia", ordinal: 999 },
  { countryCode: "ASM", countryName: "American Samoa", ordinal: 999 },
  { countryCode: "ATA", countryName: "Antarctica", ordinal: 999 },
  {
    countryCode: "ATF",
    countryName: "French Southern Territories",
    ordinal: 999,
  },
  { countryCode: "ATG", countryName: "Antigua and Barbuda", ordinal: 999 },
  { countryCode: "AUS", countryName: "Australia", ordinal: 999 },
  { countryCode: "AUT", countryName: "Austria", ordinal: 999 },
  { countryCode: "AZE", countryName: "Azerbaijan", ordinal: 999 },
  { countryCode: "BDI", countryName: "Burundi", ordinal: 999 },
  { countryCode: "BEL", countryName: "Belgium", ordinal: 999 },
  { countryCode: "BEN", countryName: "Benin", ordinal: 999 },
  {
    countryCode: "BES",
    countryName: "Bonaire, Sint Eustatius and Saba",
    ordinal: 999,
  },
  { countryCode: "BFA", countryName: "Burkina Faso", ordinal: 999 },
  { countryCode: "BGD", countryName: "Bangladesh", ordinal: 999 },
  { countryCode: "BGR", countryName: "Bulgaria", ordinal: 999 },
  { countryCode: "BHR", countryName: "Bahrain", ordinal: 999 },
  { countryCode: "BHS", countryName: "Bahamas", ordinal: 999 },
  { countryCode: "BIH", countryName: "Bosnia and Herzegovina", ordinal: 999 },
  { countryCode: "BLM", countryName: "Saint Barthélemy", ordinal: 999 },
  { countryCode: "BLR", countryName: "Belarus", ordinal: 999 },
  { countryCode: "BLZ", countryName: "Belize", ordinal: 999 },
  { countryCode: "BMU", countryName: "Bermuda", ordinal: 999 },
  {
    countryCode: "BOL",
    countryName: "Bolivia, Plurinational State of",
    ordinal: 999,
  },
  { countryCode: "BRA", countryName: "Brazil", ordinal: 999 },
  { countryCode: "BRB", countryName: "Barbados", ordinal: 999 },
  { countryCode: "BRN", countryName: "Brunei Darussalam", ordinal: 999 },
  { countryCode: "BTN", countryName: "Bhutan", ordinal: 999 },
  { countryCode: "BVT", countryName: "Bouvet Island", ordinal: 999 },
  { countryCode: "BWA", countryName: "Botswana", ordinal: 999 },
  { countryCode: "CAF", countryName: "Central African Republic", ordinal: 999 },
  { countryCode: "CAN", countryName: "Canada", ordinal: 999 },
  { countryCode: "CCK", countryName: "Cocos (Keeling) Islands", ordinal: 999 },
  { countryCode: "CHE", countryName: "Switzerland", ordinal: 999 },
  { countryCode: "CHL", countryName: "Chile", ordinal: 999 },
  { countryCode: "CHN", countryName: "China", ordinal: 999 },
  { countryCode: "CIV", countryName: "Côte d'Ivoire", ordinal: 999 },
  { countryCode: "CMR", countryName: "Cameroon", ordinal: 999 },
  {
    countryCode: "COD",
    countryName: "Congo, Democratic Republic of the",
    ordinal: 999,
  },
  { countryCode: "COG", countryName: "Congo", ordinal: 999 },
  { countryCode: "COK", countryName: "Cook Islands", ordinal: 999 },
  { countryCode: "COL", countryName: "Colombia", ordinal: 999 },
  { countryCode: "COM", countryName: "Comoros", ordinal: 999 },
  { countryCode: "CPV", countryName: "Cabo Verde", ordinal: 999 },
  { countryCode: "CRI", countryName: "Costa Rica", ordinal: 999 },
  { countryCode: "CUB", countryName: "Cuba", ordinal: 999 },
  { countryCode: "CUW", countryName: "Curaçao", ordinal: 999 },
  { countryCode: "CXR", countryName: "Christmas Island", ordinal: 999 },
  { countryCode: "CYM", countryName: "Cayman Islands", ordinal: 999 },
  { countryCode: "CYP", countryName: "Cyprus", ordinal: 999 },
  { countryCode: "CZE", countryName: "Czechia", ordinal: 999 },
  { countryCode: "DEU", countryName: "Germany", ordinal: 999 },
  { countryCode: "DJI", countryName: "Djibouti", ordinal: 999 },
  { countryCode: "DMA", countryName: "Dominica", ordinal: 999 },
  { countryCode: "DNK", countryName: "Denmark", ordinal: 999 },
  { countryCode: "DOM", countryName: "Dominican Republic", ordinal: 999 },
  { countryCode: "DZA", countryName: "Algeria", ordinal: 999 },
  { countryCode: "ECU", countryName: "Ecuador", ordinal: 999 },
  { countryCode: "EGY", countryName: "Egypt", ordinal: 999 },
  { countryCode: "ERI", countryName: "Eritrea", ordinal: 999 },
  { countryCode: "ESH", countryName: "Western Sahara", ordinal: 999 },
  { countryCode: "ESP", countryName: "Spain", ordinal: 999 },
  { countryCode: "EST", countryName: "Estonia", ordinal: 999 },
  { countryCode: "ETH", countryName: "Ethiopia", ordinal: 999 },
  { countryCode: "FIN", countryName: "Finland", ordinal: 999 },
  { countryCode: "FJI", countryName: "Fiji", ordinal: 999 },
  {
    countryCode: "FLK",
    countryName: "Falkland Islands (Malvinas)",
    ordinal: 999,
  },
  { countryCode: "FRA", countryName: "France", ordinal: 999 },
  { countryCode: "FRO", countryName: "Faroe Islands", ordinal: 999 },
  {
    countryCode: "FSM",
    countryName: "Micronesia, Federated States of",
    ordinal: 999,
  },
  { countryCode: "GAB", countryName: "Gabon", ordinal: 999 },
  {
    countryCode: "GBR",
    countryName: "United Kingdom of Great Britain and Northern Ireland",
    ordinal: 999,
  },
  { countryCode: "GEO", countryName: "Georgia", ordinal: 999 },
  { countryCode: "GGY", countryName: "Guernsey", ordinal: 999 },
  { countryCode: "GHA", countryName: "Ghana", ordinal: 999 },
  { countryCode: "GIB", countryName: "Gibraltar", ordinal: 999 },
  { countryCode: "GIN", countryName: "Guinea", ordinal: 999 },
  { countryCode: "GLP", countryName: "Guadeloupe", ordinal: 999 },
  { countryCode: "GMB", countryName: "Gambia", ordinal: 999 },
  { countryCode: "GNB", countryName: "Guinea-Bissau", ordinal: 999 },
  { countryCode: "GNQ", countryName: "Equatorial Guinea", ordinal: 999 },
  { countryCode: "GRC", countryName: "Greece", ordinal: 999 },
  { countryCode: "GRD", countryName: "Grenada", ordinal: 999 },
  { countryCode: "GRL", countryName: "Greenland", ordinal: 999 },
  { countryCode: "GTM", countryName: "Guatemala", ordinal: 999 },
  { countryCode: "GUF", countryName: "French Guiana", ordinal: 999 },
  { countryCode: "GUM", countryName: "Guam", ordinal: 999 },
  { countryCode: "GUY", countryName: "Guyana", ordinal: 999 },
  { countryCode: "HKG", countryName: "Hong Kong", ordinal: 999 },
  {
    countryCode: "HMD",
    countryName: "Heard Island and McDonald Islands",
    ordinal: 999,
  },
  { countryCode: "HND", countryName: "Honduras", ordinal: 999 },
  { countryCode: "HRV", countryName: "Croatia", ordinal: 999 },
  { countryCode: "HTI", countryName: "Haiti", ordinal: 999 },
  { countryCode: "HUN", countryName: "Hungary", ordinal: 999 },
  { countryCode: "IDN", countryName: "Indonesia", ordinal: 999 },
  { countryCode: "IMN", countryName: "Isle of Man", ordinal: 999 },
  { countryCode: "IND", countryName: "India", ordinal: 999 },
  {
    countryCode: "IOT",
    countryName: "British Indian Ocean Territory",
    ordinal: 999,
  },
  { countryCode: "IRL", countryName: "Ireland", ordinal: 999 },
  {
    countryCode: "IRN",
    countryName: "Iran, Islamic Republic of",
    ordinal: 999,
  },
  { countryCode: "IRQ", countryName: "Iraq", ordinal: 999 },
  { countryCode: "ISL", countryName: "Iceland", ordinal: 999 },
  { countryCode: "ISR", countryName: "Israel", ordinal: 999 },
  { countryCode: "ITA", countryName: "Italy", ordinal: 999 },
  { countryCode: "JAM", countryName: "Jamaica", ordinal: 999 },
  { countryCode: "JEY", countryName: "Jersey", ordinal: 999 },
  { countryCode: "JOR", countryName: "Jordan", ordinal: 999 },
  { countryCode: "JPN", countryName: "Japan", ordinal: 999 },
  { countryCode: "KAZ", countryName: "Kazakhstan", ordinal: 999 },
  { countryCode: "KEN", countryName: "Kenya", ordinal: 999 },
  { countryCode: "KGZ", countryName: "Kyrgyzstan", ordinal: 999 },
  { countryCode: "KHM", countryName: "Cambodia", ordinal: 999 },
  { countryCode: "KIR", countryName: "Kiribati", ordinal: 999 },
  { countryCode: "KNA", countryName: "Saint Kitts and Nevis", ordinal: 999 },
  { countryCode: "KOR", countryName: "Korea, Republic of", ordinal: 999 },
  { countryCode: "KWT", countryName: "Kuwait", ordinal: 999 },
  {
    countryCode: "LAO",
    countryName: "Lao People's Democratic Republic",
    ordinal: 999,
  },
  { countryCode: "LBN", countryName: "Lebanon", ordinal: 999 },
  { countryCode: "LBR", countryName: "Liberia", ordinal: 999 },
  { countryCode: "LBY", countryName: "Libya", ordinal: 999 },
  { countryCode: "LCA", countryName: "Saint Lucia", ordinal: 999 },
  { countryCode: "LIE", countryName: "Liechtenstein", ordinal: 999 },
  { countryCode: "LKA", countryName: "Sri Lanka", ordinal: 999 },
  { countryCode: "LSO", countryName: "Lesotho", ordinal: 999 },
  { countryCode: "LTU", countryName: "Lithuania", ordinal: 999 },
  { countryCode: "LUX", countryName: "Luxembourg", ordinal: 999 },
  { countryCode: "LVA", countryName: "Latvia", ordinal: 999 },
  { countryCode: "MAC", countryName: "Macao", ordinal: 999 },
  {
    countryCode: "MAF",
    countryName: "Saint Martin (French part)",
    ordinal: 999,
  },
  { countryCode: "MAR", countryName: "Morocco", ordinal: 999 },
  { countryCode: "MCO", countryName: "Monaco", ordinal: 999 },
  { countryCode: "MDA", countryName: "Moldova, Republic of", ordinal: 999 },
  { countryCode: "MDG", countryName: "Madagascar", ordinal: 999 },
  { countryCode: "MDV", countryName: "Maldives", ordinal: 999 },
  { countryCode: "MEX", countryName: "Mexico", ordinal: 999 },
  { countryCode: "MHL", countryName: "Marshall Islands", ordinal: 999 },
  { countryCode: "MKD", countryName: "North Macedonia", ordinal: 999 },
  { countryCode: "MLI", countryName: "Mali", ordinal: 999 },
  { countryCode: "MLT", countryName: "Malta", ordinal: 999 },
  { countryCode: "MMR", countryName: "Myanmar", ordinal: 999 },
  { countryCode: "MNE", countryName: "Montenegro", ordinal: 999 },
  { countryCode: "MNG", countryName: "Mongolia", ordinal: 999 },
  { countryCode: "MNP", countryName: "Northern Mariana Islands", ordinal: 999 },
  { countryCode: "MOZ", countryName: "Mozambique", ordinal: 999 },
  { countryCode: "MRT", countryName: "Mauritania", ordinal: 999 },
  { countryCode: "MSR", countryName: "Montserrat", ordinal: 999 },
  { countryCode: "MTQ", countryName: "Martinique", ordinal: 999 },
  { countryCode: "MUS", countryName: "Mauritius", ordinal: 999 },
  { countryCode: "MWI", countryName: "Malawi", ordinal: 999 },
  { countryCode: "MYS", countryName: "Malaysia", ordinal: 999 },
  { countryCode: "MYT", countryName: "Mayotte", ordinal: 999 },
  { countryCode: "NAM", countryName: "Namibia", ordinal: 999 },
  { countryCode: "NCL", countryName: "New Caledonia", ordinal: 999 },
  { countryCode: "NER", countryName: "Niger", ordinal: 999 },
  { countryCode: "NFK", countryName: "Norfolk Island", ordinal: 999 },
  { countryCode: "NGA", countryName: "Nigeria", ordinal: 999 },
  { countryCode: "NIC", countryName: "Nicaragua", ordinal: 999 },
  { countryCode: "NIU", countryName: "Niue", ordinal: 999 },
  {
    countryCode: "NLD",
    countryName: "Netherlands, Kingdom of the",
    ordinal: 999,
  },
  { countryCode: "NOR", countryName: "Norway", ordinal: 999 },
  { countryCode: "NPL", countryName: "Nepal", ordinal: 999 },
  { countryCode: "NRU", countryName: "Nauru", ordinal: 999 },
  { countryCode: "NZL", countryName: "New Zealand", ordinal: 999 },
  { countryCode: "OMN", countryName: "Oman", ordinal: 999 },
  { countryCode: "PAK", countryName: "Pakistan", ordinal: 999 },
  { countryCode: "PAN", countryName: "Panama", ordinal: 999 },
  { countryCode: "PCN", countryName: "Pitcairn", ordinal: 999 },
  { countryCode: "PER", countryName: "Peru", ordinal: 999 },
  { countryCode: "PHL", countryName: "Philippines", ordinal: 999 },
  { countryCode: "PLW", countryName: "Palau", ordinal: 999 },
  { countryCode: "PNG", countryName: "Papua New Guinea", ordinal: 999 },
  { countryCode: "POL", countryName: "Poland", ordinal: 999 },
  { countryCode: "PRI", countryName: "Puerto Rico", ordinal: 999 },
  {
    countryCode: "PRK",
    countryName: "Korea, Democratic People's Republic of",
    ordinal: 999,
  },
  { countryCode: "PRT", countryName: "Portugal", ordinal: 999 },
  { countryCode: "PRY", countryName: "Paraguay", ordinal: 999 },
  { countryCode: "PSE", countryName: "Palestine, State of", ordinal: 999 },
  { countryCode: "PYF", countryName: "French Polynesia", ordinal: 999 },
  { countryCode: "QAT", countryName: "Qatar", ordinal: 999 },
  { countryCode: "REU", countryName: "Réunion", ordinal: 999 },
  { countryCode: "ROU", countryName: "Romania", ordinal: 999 },
  { countryCode: "RUS", countryName: "Russian Federation", ordinal: 999 },
  { countryCode: "RWA", countryName: "Rwanda", ordinal: 999 },
  { countryCode: "SAU", countryName: "Saudi Arabia", ordinal: 999 },
  { countryCode: "SDN", countryName: "Sudan", ordinal: 999 },
  { countryCode: "SEN", countryName: "Senegal", ordinal: 999 },
  { countryCode: "SGP", countryName: "Singapore", ordinal: 999 },
  {
    countryCode: "SGS",
    countryName: "South Georgia and the South Sandwich Islands",
    ordinal: 999,
  },
  {
    countryCode: "SHN",
    countryName: "Saint Helena, Ascension and Tristan da Cunha",
    ordinal: 999,
  },
  { countryCode: "SJM", countryName: "Svalbard and Jan Mayen", ordinal: 999 },
  { countryCode: "SLB", countryName: "Solomon Islands", ordinal: 999 },
  { countryCode: "SLE", countryName: "Sierra Leone", ordinal: 999 },
  { countryCode: "SLV", countryName: "El Salvador", ordinal: 999 },
  { countryCode: "SMR", countryName: "San Marino", ordinal: 999 },
  { countryCode: "SOM", countryName: "Somalia", ordinal: 999 },
  {
    countryCode: "SPM",
    countryName: "Saint Pierre and Miquelon",
    ordinal: 999,
  },
  { countryCode: "SRB", countryName: "Serbia", ordinal: 999 },
  { countryCode: "SSD", countryName: "South Sudan", ordinal: 999 },
  { countryCode: "STP", countryName: "Sao Tome and Principe", ordinal: 999 },
  { countryCode: "SUR", countryName: "Suriname", ordinal: 999 },
  { countryCode: "SVK", countryName: "Slovakia", ordinal: 999 },
  { countryCode: "SVN", countryName: "Slovenia", ordinal: 999 },
  { countryCode: "SWE", countryName: "Sweden", ordinal: 999 },
  { countryCode: "SWZ", countryName: "Eswatini", ordinal: 999 },
  {
    countryCode: "SXM",
    countryName: "Sint Maarten (Dutch part)",
    ordinal: 999,
  },
  { countryCode: "SYC", countryName: "Seychelles", ordinal: 999 },
  { countryCode: "SYR", countryName: "Syrian Arab Republic", ordinal: 999 },
  { countryCode: "TCA", countryName: "Turks and Caicos Islands", ordinal: 999 },
  { countryCode: "TCD", countryName: "Chad", ordinal: 999 },
  { countryCode: "TGO", countryName: "Togo", ordinal: 999 },
  { countryCode: "THA", countryName: "Thailand", ordinal: 999 },
  { countryCode: "TJK", countryName: "Tajikistan", ordinal: 999 },
  { countryCode: "TKL", countryName: "Tokelau", ordinal: 999 },
  { countryCode: "TKM", countryName: "Turkmenistan", ordinal: 999 },
  { countryCode: "TLS", countryName: "Timor-Leste", ordinal: 999 },
  { countryCode: "TON", countryName: "Tonga", ordinal: 999 },
  { countryCode: "TTO", countryName: "Trinidad and Tobago", ordinal: 999 },
  { countryCode: "TUN", countryName: "Tunisia", ordinal: 999 },
  { countryCode: "TUR", countryName: "Türkiye", ordinal: 999 },
  { countryCode: "TUV", countryName: "Tuvalu", ordinal: 999 },
  {
    countryCode: "TWN",
    countryName: "Taiwan, Province of China",
    ordinal: 999,
  },
  {
    countryCode: "TZA",
    countryName: "Tanzania, United Republic of",
    ordinal: 999,
  },
  { countryCode: "UGA", countryName: "Uganda", ordinal: 999 },
  { countryCode: "UKR", countryName: "Ukraine", ordinal: 999 },
  {
    countryCode: "UMI",
    countryName: "United States Minor Outlying Islands",
    ordinal: 999,
  },
  { countryCode: "URY", countryName: "Uruguay", ordinal: 999 },
  { countryCode: "UZB", countryName: "Uzbekistan", ordinal: 999 },
  { countryCode: "VAT", countryName: "Holy See", ordinal: 999 },
  {
    countryCode: "VCT",
    countryName: "Saint Vincent and the Grenadines",
    ordinal: 999,
  },
  {
    countryCode: "VEN",
    countryName: "Venezuela, Bolivarian Republic of",
    ordinal: 999,
  },
  { countryCode: "VGB", countryName: "Virgin Islands (British)", ordinal: 999 },
  { countryCode: "VIR", countryName: "Virgin Islands (U.S.)", ordinal: 999 },
  { countryCode: "VNM", countryName: "Viet Nam", ordinal: 999 },
  { countryCode: "VUT", countryName: "Vanuatu", ordinal: 999 },
  { countryCode: "WLF", countryName: "Wallis and Futuna", ordinal: 999 },
  { countryCode: "WSM", countryName: "Samoa", ordinal: 999 },
  { countryCode: "YEM", countryName: "Yemen", ordinal: 999 },
  { countryCode: "ZAF", countryName: "South Africa", ordinal: 999 },
  { countryCode: "ZMB", countryName: "Zambia", ordinal: 999 },
  { countryCode: "ZWE", countryName: "Zimbabwe", ordinal: 999 },
];
