interface language {
  languageCode: string;
  languageName: string;
  ordinal: number;
}

export const LanguageCodes: language[] = [
  { languageCode: "EN", languageName: "English", ordinal: 0 },
  { languageCode: "AR", languageName: "Arabic", ordinal: 1 },
  { languageCode: "ZH", languageName: "Chinese", ordinal: 1 },
  { languageCode: "FR", languageName: "French", ordinal: 1 },
  { languageCode: "DE", languageName: "German", ordinal: 1 },
  { languageCode: "HI", languageName: "Hindi", ordinal: 1 },
  { languageCode: "ES", languageName: "Spanish", ordinal: 1 },
  { languageCode: "AB", languageName: "Abkhazian", ordinal: 999 },
  { languageCode: "AA", languageName: "Afar", ordinal: 999 },
  { languageCode: "AF", languageName: "Afrikaans", ordinal: 999 },
  { languageCode: "AK", languageName: "Akan", ordinal: 999 },
  { languageCode: "SQ", languageName: "Albanian", ordinal: 999 },
  { languageCode: "AM", languageName: "Amharic", ordinal: 999 },
  { languageCode: "AN", languageName: "Aragonese", ordinal: 999 },
  { languageCode: "HY", languageName: "Armenian", ordinal: 999 },
  { languageCode: "AS", languageName: "Assamese", ordinal: 999 },
  { languageCode: "AV", languageName: "Avaric", ordinal: 999 },
  { languageCode: "AY", languageName: "Aymara", ordinal: 999 },
  { languageCode: "AZ", languageName: "Azerbaijani", ordinal: 999 },
  { languageCode: "BM", languageName: "Bambara", ordinal: 999 },
  { languageCode: "BA", languageName: "Bashkir", ordinal: 999 },
  { languageCode: "EU", languageName: "Basque", ordinal: 999 },
  { languageCode: "BE", languageName: "Belarusian", ordinal: 999 },
  { languageCode: "BN", languageName: "Bengali", ordinal: 999 },
  { languageCode: "BI", languageName: "Bislama", ordinal: 999 },
  { languageCode: "BS", languageName: "Bosnian", ordinal: 999 },
  { languageCode: "BR", languageName: "Breton", ordinal: 999 },
  { languageCode: "BG", languageName: "Bulgarian", ordinal: 999 },
  { languageCode: "MY", languageName: "Burmese", ordinal: 999 },
  { languageCode: "CA", languageName: "Catalan", ordinal: 999 },
  { languageCode: "KM", languageName: "Central Khmer", ordinal: 999 },
  { languageCode: "CH", languageName: "Chamorro", ordinal: 999 },
  { languageCode: "CE", languageName: "Chechen", ordinal: 999 },
  { languageCode: "NY", languageName: "Chichewa", ordinal: 999 },
  { languageCode: "CV", languageName: "Chuvash", ordinal: 999 },
  { languageCode: "KW", languageName: "Cornish", ordinal: 999 },
  { languageCode: "CO", languageName: "Corsican", ordinal: 999 },
  { languageCode: "CR", languageName: "Cree", ordinal: 999 },
  { languageCode: "HR", languageName: "Croatian", ordinal: 999 },
  { languageCode: "CS", languageName: "Czech", ordinal: 999 },
  { languageCode: "DA", languageName: "Danish", ordinal: 999 },
  { languageCode: "DV", languageName: "Divehi", ordinal: 999 },
  { languageCode: "NL", languageName: "Dutch", ordinal: 999 },
  { languageCode: "DZ", languageName: "Dzongkha", ordinal: 999 },
  { languageCode: "ET", languageName: "Estonian", ordinal: 999 },
  { languageCode: "EE", languageName: "Ewe", ordinal: 999 },
  { languageCode: "FO", languageName: "Faroese", ordinal: 999 },
  { languageCode: "FJ", languageName: "Fijian", ordinal: 999 },
  { languageCode: "FI", languageName: "Finnish", ordinal: 999 },
  { languageCode: "FF", languageName: "Fulah", ordinal: 999 },
  { languageCode: "GD", languageName: "Gaelic", ordinal: 999 },
  { languageCode: "GL", languageName: "Galician", ordinal: 999 },
  { languageCode: "LG", languageName: "Ganda", ordinal: 999 },
  { languageCode: "KA", languageName: "Georgian", ordinal: 999 },
  { languageCode: "EL", languageName: "Greek", ordinal: 999 },
  { languageCode: "GN", languageName: "Guarani", ordinal: 999 },
  { languageCode: "GU", languageName: "Gujarati", ordinal: 999 },
  { languageCode: "HT", languageName: "Haitian", ordinal: 999 },
  { languageCode: "HA", languageName: "Hausa", ordinal: 999 },
  { languageCode: "HAw", languageName: "Hawaiian", ordinal: 999 },
  { languageCode: "HE", languageName: "Hebrew", ordinal: 999 },
  { languageCode: "HZ", languageName: "Herero", ordinal: 999 },
  { languageCode: "HO", languageName: "Hiri Motu", ordinal: 999 },
  { languageCode: "HU", languageName: "Hungarian", ordinal: 999 },
  { languageCode: "IS", languageName: "Icelandic", ordinal: 999 },
  { languageCode: "IG", languageName: "Igbo", ordinal: 999 },
  { languageCode: "ID", languageName: "Indonesian", ordinal: 999 },
  { languageCode: "IU", languageName: "Inuktitut", ordinal: 999 },
  { languageCode: "IK", languageName: "Inupiaq", ordinal: 999 },
  { languageCode: "GA", languageName: "Irish", ordinal: 999 },
  { languageCode: "IT", languageName: "Italian", ordinal: 999 },
  { languageCode: "JA", languageName: "Japanese", ordinal: 999 },
  { languageCode: "JV", languageName: "Javanese", ordinal: 999 },
  { languageCode: "KL", languageName: "Kalaallisut", ordinal: 999 },
  { languageCode: "KN", languageName: "Kannada", ordinal: 999 },
  { languageCode: "KR", languageName: "Kanuri", ordinal: 999 },
  { languageCode: "KS", languageName: "Kashmiri", ordinal: 999 },
  { languageCode: "KK", languageName: "Kazakh", ordinal: 999 },
  { languageCode: "KI", languageName: "Kikuyu", ordinal: 999 },
  { languageCode: "RW", languageName: "Kinyarwanda", ordinal: 999 },
  { languageCode: "KV", languageName: "Komi", ordinal: 999 },
  { languageCode: "KG", languageName: "Kongo", ordinal: 999 },
  { languageCode: "KO", languageName: "Korean", ordinal: 999 },
  { languageCode: "KJ", languageName: "Kuanyama", ordinal: 999 },
  { languageCode: "KU", languageName: "Kurdish", ordinal: 999 },
  { languageCode: "KY", languageName: "Kyrgyz", ordinal: 999 },
  { languageCode: "LO", languageName: "Lao", ordinal: 999 },
  { languageCode: "LV", languageName: "Latvian", ordinal: 999 },
  { languageCode: "LI", languageName: "Limburgan", ordinal: 999 },
  { languageCode: "LN", languageName: "Lingala", ordinal: 999 },
  { languageCode: "LT", languageName: "Lithuanian", ordinal: 999 },
  { languageCode: "LU", languageName: "Luba-Katanga", ordinal: 999 },
  { languageCode: "LB", languageName: "Luxembourgish", ordinal: 999 },
  { languageCode: "MK", languageName: "Macedonian", ordinal: 999 },
  { languageCode: "MG", languageName: "Malagasy", ordinal: 999 },
  { languageCode: "MS", languageName: "Malay", ordinal: 999 },
  { languageCode: "ML", languageName: "Malayalam", ordinal: 999 },
  { languageCode: "MT", languageName: "Maltese", ordinal: 999 },
  { languageCode: "GV", languageName: "Manx", ordinal: 999 },
  { languageCode: "MI", languageName: "Maori", ordinal: 999 },
  { languageCode: "MR", languageName: "Marathi", ordinal: 999 },
  { languageCode: "MH", languageName: "Marshallese", ordinal: 999 },
  { languageCode: "MN", languageName: "Mongolian", ordinal: 999 },
  { languageCode: "NA", languageName: "Nauru", ordinal: 999 },
  { languageCode: "NV", languageName: "Navajo", ordinal: 999 },
  { languageCode: "NG", languageName: "Ndonga", ordinal: 999 },
  { languageCode: "NE", languageName: "Nepali", ordinal: 999 },
  { languageCode: "ND", languageName: "North Ndebele", ordinal: 999 },
  { languageCode: "SE", languageName: "Northern Sami", ordinal: 999 },
  { languageCode: "NO", languageName: "Norwegian", ordinal: 999 },
  { languageCode: "NB", languageName: "Norwegian Bokmål", ordinal: 999 },
  { languageCode: "NN", languageName: "Norwegian Nynorsk", ordinal: 999 },
  { languageCode: "OC", languageName: "Occitan", ordinal: 999 },
  { languageCode: "OJ", languageName: "Ojibwa", ordinal: 999 },
  { languageCode: "OR", languageName: "Oriya", ordinal: 999 },
  { languageCode: "OM", languageName: "Oromo", ordinal: 999 },
  { languageCode: "OS", languageName: "Ossetian", ordinal: 999 },
  { languageCode: "PS", languageName: "Pashto", ordinal: 999 },
  { languageCode: "FA", languageName: "Persian", ordinal: 999 },
  { languageCode: "PL", languageName: "Polish", ordinal: 999 },
  { languageCode: "PT", languageName: "Portuguese", ordinal: 999 },
  { languageCode: "PA", languageName: "Punjabi, Panjabi", ordinal: 999 },
  { languageCode: "QU", languageName: "Quechua", ordinal: 999 },
  { languageCode: "RO", languageName: "Romanian", ordinal: 999 },
  { languageCode: "RM", languageName: "Romansh", ordinal: 999 },
  { languageCode: "RN", languageName: "Rundi", ordinal: 999 },
  { languageCode: "RU", languageName: "Russian", ordinal: 999 },
  { languageCode: "SM", languageName: "Samoan", ordinal: 999 },
  { languageCode: "SG", languageName: "Sango", ordinal: 999 },
  { languageCode: "SC", languageName: "Sardinian", ordinal: 999 },
  { languageCode: "SR", languageName: "Serbian", ordinal: 999 },
  { languageCode: "SN", languageName: "Shona", ordinal: 999 },
  { languageCode: "II", languageName: "Sichuan Yi", ordinal: 999 },
  { languageCode: "SD", languageName: "Sindhi", ordinal: 999 },
  { languageCode: "SI", languageName: "Sinhala", ordinal: 999 },
  { languageCode: "SK", languageName: "Slovak", ordinal: 999 },
  { languageCode: "SL", languageName: "Slovenian", ordinal: 999 },
  { languageCode: "SO", languageName: "Somali", ordinal: 999 },
  { languageCode: "NR", languageName: "South Ndebele", ordinal: 999 },
  { languageCode: "ST", languageName: "Southern Sotho", ordinal: 999 },
  { languageCode: "SU", languageName: "Sundanese", ordinal: 999 },
  { languageCode: "SW", languageName: "Swahili", ordinal: 999 },
  { languageCode: "SS", languageName: "Swati", ordinal: 999 },
  { languageCode: "SV", languageName: "Swedish", ordinal: 999 },
  { languageCode: "TL", languageName: "Tagalog", ordinal: 999 },
  { languageCode: "TY", languageName: "Tahitian", ordinal: 999 },
  { languageCode: "TG", languageName: "Tajik", ordinal: 999 },
  { languageCode: "TA", languageName: "Tamil", ordinal: 999 },
  { languageCode: "TT", languageName: "Tatar", ordinal: 999 },
  { languageCode: "TE", languageName: "Telugu", ordinal: 999 },
  { languageCode: "TH", languageName: "Thai", ordinal: 999 },
  { languageCode: "BO", languageName: "Tibetan", ordinal: 999 },
  { languageCode: "TI", languageName: "Tigrinya", ordinal: 999 },
  { languageCode: "TO", languageName: "Tonga", ordinal: 999 },
  { languageCode: "TS", languageName: "Tsonga", ordinal: 999 },
  { languageCode: "TN", languageName: "Tswana", ordinal: 999 },
  { languageCode: "TR", languageName: "Turkish", ordinal: 999 },
  { languageCode: "TK", languageName: "Turkmen", ordinal: 999 },
  { languageCode: "TW", languageName: "Twi", ordinal: 999 },
  { languageCode: "UG", languageName: "Uighur", ordinal: 999 },
  { languageCode: "UK", languageName: "Ukrainian", ordinal: 999 },
  { languageCode: "UR", languageName: "Urdu", ordinal: 999 },
  { languageCode: "UZ", languageName: "Uzbek", ordinal: 999 },
  { languageCode: "VE", languageName: "Venda", ordinal: 999 },
  { languageCode: "VI", languageName: "Vietnamese", ordinal: 999 },
  { languageCode: "WA", languageName: "Walloon", ordinal: 999 },
  { languageCode: "CY", languageName: "Welsh", ordinal: 999 },
  { languageCode: "FY", languageName: "Western Frisian", ordinal: 999 },
  { languageCode: "WO", languageName: "Wolof", ordinal: 999 },
  { languageCode: "XH", languageName: "Xhosa", ordinal: 999 },
  { languageCode: "YI", languageName: "Yiddish", ordinal: 999 },
  { languageCode: "YO", languageName: "Yoruba", ordinal: 999 },
  { languageCode: "ZA", languageName: "Zhuang, Chuang", ordinal: 999 },
  { languageCode: "ZU", languageName: "Zulu", ordinal: 999 },
];
